unique_ids:
  assets:
    standard-page.html: C7ZLVYTLCX6X23M2AF3DIFAFGX3U25BQ
    theme.css: DCIBYQREJSNDIKA5G4BZ5OMW3INGXRSU
  forms:
    Form1: 4Z7X2YBJJYJILUDRCBYUZWB3TTRCVB4M
    Form1.ItemTemplate1: '1733789322409341274272800.0544'
  modules: {}
  scripts: {}
  server_modules: {}
