unique_ids:
  assets:
    standard-page.html: C7ZLVYTLCX6X23M2AF3DIFAFGX3U25BQ
    theme.css: DCIBYQREJSNDIKA5G4BZ5OMW3INGXRSU
  forms:
    Form1: 4Z7X2YBJJYJILUDRCBYUZWB3TTRCVB4M
    Form1.ItemTemplate2: '1733793049079876746607682.0479'
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1733792960276216939282756.1898'
